---
format: 
  pdf:
    include-before-body:
      - dokumentobjekter/texstuff/forside.tex  
    geometry:
      - top=20mm
      - left=20mm
      - heightrounded
    fontsize: 12pt
    mainfont: Times New Roman
    documentclass: scrartcl
    papersize: a4
    toccolor: black
    toc-depth: 2
    number-sections: true
execute:
  enabled: true
echo: false
message: false
warning: false
bibliography: dokumentobjekter/texstuff/references.bib
csl: dokumentobjekter/texstuff/norsk-apa-manual.csl
header-includes:
  - \usepackage{wrapfig}
  - \usepackage{subcaption}
  - \usepackage{amsmath}
  - \usepackage{cancel}
  - \usepackage{hyperref}
  - \usepackage{tikz}
  - \usepackage{setspace}
  - \setstretch{1.5}
  - \usetikzlibrary{shapes.geometric, arrows, arrows.meta, positioning, calc}
  - \usepackage{tabularx}
  - \renewcommand{\maketitle}{}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{} 
  - \fancyhead[L]{\rightmark}
  - \fancyhead[R]{\thepage}
  - \fancyfoot[C]{\thepage}
  - \usepackage{colortbl}
  - \definecolor{cornflowerblue}{RGB}{100,149,237}
  - \definecolor{darkblue}{RGB}{115,150,255}
  - \definecolor{lighterblue}{RGB}{131, 191, 212} 
  - \definecolor{lightblue}{RGB}{178,211,220}
nocite: |
  @*
---







\hypersetup{linkcolor=black}
\renewcommand{\contentsname}{Innholdsfortegnelse}
\renewcommand*{\figureautorefname}{Figur}
\renewcommand*{\tableautorefname}{Tabell}
\renewcommand*{\equationautorefname}{Ligning}
\renewcommand*{\sectionautorefname}{Kapittel}
\renewcommand*{\subsectionautorefname}{Underkapittel}
\renewcommand*{\subsubsectionautorefname}{Delkapittel}
\tableofcontents
\listoffigures
\hypersetup{linkcolor=blue}
\newpage
\thispagestyle{plain}
\begin{center}
    \Large
    \textbf{Abstract}
\end{center}



blabla blir fjerna




\newpage




##




Alle studenter leverer en separat innleveringsoppgave. Oppgaven tar for seg artikkelen gruppen presenterte.

Besvar spørsmålene nedenfor i form av ett sett med slides som dere presenterer, og lever i Wiseflow innen 18. oktober.

## 3.1 Del 1 — Artikkelens innhold og metode

### Spørsmål 1.1 Hva handlet artikkelen om?

### Spørsmål 1.2 Hvilke spørsmål forsøkte artikkelen å svare på?

### Spørsmål 1.3 Hvilke metoder brukte artikkelen for å svare på spørsmålet?

## 3.2 Del 2 — Påstander og begrunnelse

### Spørsmål 2.1 Hvilke nye påstander etablerer artikkelen? Hvordan bygger disse påstandene på tidligere forskning, logikk eller empiriske funn?

### Spørsmål 2.2 Ble noen hypoteser satt opp og avkreftet?

### Spørsmål 2.3 Hvordan begrunnet forfatteren rimeligheten av hypotesene sine?

## 3.3 Del 3 — Relevans

### Spørsmål 3.1 Hva er den vitenskapelige eller samfunnsmessige relevansen av innsikten artikkelen etablerer?

## 3.4 Del 4 — Videre forskning

### Spørsmål 4.1 Hvilke nye spørsmål reises ved artikkelen? Hvordan har artikler som refererer til dette arbeidet, og som er relatert til det, besvart disse spørsmålene? Bruk Google Scholar til å besvare dette.


Obligatorisk oppgave Gruppepresentasjon og individuell innlevering

## 3.5 Del 5 — Empirisk eller teoretisk arbeid

### Spørsmål 5.1 Dersom det var et empirisk arbeid: Forklar hvilke data artikkelen ser på, og hvordan dataene analyseres. Hva er de viktige valgene forfatteren har gjort i dataanalysen? Kan du forsøke å tenke gjennom hvordan arbeidet hadde vært dersom forfatteren hadde gjort andre valg?

Dersom artikkelen var et teoretisk arbeid: Hva beviser forfatteren, og hvordan?

Hvilke antagelser bygger resultatene på? Kan du forklare hvorfor det teoretiske resultatet kan være interessant og skape innsikt også i situasjoner der antakelsene
ikke er oppfylt?



\clearpage

# References

::: {#refs}

::: 


# Appendix

\appendix

\section{Appendix General AI Use}

When we write code in Visual Studio Code or RStudio, we use a plugin called GitHub Copilot. This plugin will try to suggest code or sentences(even paragraphs) as we are writing. We sometimes accept the suggestions but only if it's how we would do it. There are also cases where it can be seen in the code that we comment with a "plotting year on x, value on y" so that it will just autofill the code we usually use. Documenting each of these instances would be cumbersome and wouldn't serve any purpose. All code sections with such comments can be assumed to have involved GitHub Copilot. More information about this AI tool is available at <https://github.com/features/copilot>.




