---
format: 
  pdf:
    geometry:
      - top=20mm
      - left=20mm
      - heightrounded
    fontsize: 12pt
    mainfont: Times New Roman
    documentclass: scrartcl
    papersize: a4
    toc-title: "Innholdsfortegnelse"
    toccolor: black
    toc-depth: 2
echo: true
message: false
warning: false
bibliography: dokumentobjekter/texstuff/references.bib
csl: dokumentobjekter/texstuff/norsk-apa-manual.csl
crossref: 
  lof-title: "Figurliste"
  fig-title: "Figur"
  lot-title: "Tabelliste"
  tbl-title: "Tabell"
header-includes:
  - \usepackage{wrapfig}
  - \usepackage{subcaption}
  - \usepackage{amsmath}
  - \usepackage{cancel}
  - \usepackage{hyperref}
  - \usepackage{tikz}
  - \usepackage{setspace}
  - \setstretch{1.5}
  - \usetikzlibrary{shapes.geometric, arrows, arrows.meta, positioning, calc}
  - \usepackage{tabularx}
  - \renewcommand{\maketitle}{}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{} 
  - \fancyhead[L]{\rightmark}
  - \fancyhead[R]{\thepage}
  - \fancyfoot[C]{\thepage}
  - \usepackage{colortbl}
  - \definecolor{cornflowerblue}{RGB}{100,149,237}
  - \definecolor{darkblue}{RGB}{115,150,255}
  - \definecolor{lighterblue}{RGB}{131, 191, 212} 
  - \definecolor{lightblue}{RGB}{178,211,220}
keep-tex: false
nocite: |
  @*
---

```{r, include=FALSE}
# Load necessary libraries
library(tidyverse)
```

# Avinor - Project

```{r}
# Loading csv to look at the data

airports <- read_csv("data/airportgroups.csv")
historical_flights <- read_csv("data/historical_flights.csv")
inference_data_oct2025 <- read_csv("data/inference_data_oct2025.csv")
preds_mal <- read_csv("data/preds_mal.csv")
schedule_oct2025 <- read_csv("data/schedule_oct2025.csv")
training_data <- read_csv("data/training_data.csv")
```
